schema_version: 1

context:
  name: trackio
  version: "0.20.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/gradio-app/trackio/archive/refs/tags/trackio@${{ version }}.tar.gz
  sha256: 20debd60dd47e6a084bfca5752b85d62471edb13e2613a4f8504a306649b7cde

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - trackio = trackio.cli:main
  number: 0

requirements:
  host:
    - python  ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python  >=${{ python_min }}
    - pandas <3.0.0
    - huggingface_hub <2.0.0
    - gradio >=6.10.0,<7.0.0
    - numpy <3.0.0
    - pillow <12.0.0
    - orjson >=3.0,<4.0.0
    - pydub <1.0.0
    - plotly >=6.0.0,<7.0.0
  run_constraints:
    - tbparse ==0.0.9
    - tensorboardx >=2.0.0,<3.0.0
    - nvidia-ml-py >=12.0.0
    - pyarrow >=21.0

tests:
  - script:
      - trackio --help
  - python:
      python_version: ${{ python_min }}.*
      pip_check: true
      imports:
        - trackio

about:
  homepage: https://github.com/gradio-app/trackio
  summary: 'A lightweight, local-first and free experiment tracking library built by Hugging Face'
  description: |
    trackio is a lightweight, free experiment tracking Python library built by Hugging Face.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/gradio-app/trackio

extra:
  recipe-maintainers:
    - flferretti
